apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testdisk-pvc
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv
  namespace: default
spec:
  containers:
  - name: nginx-pv
    image: nginx
    volumeMounts:
    - name: testdisk-pv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: testdisk-pv
    persistentVolumeClaim:
      claimName: testdisk-pvc
